export default {
  SIDEBAR_TOGGLE: 'sidebarToggle',
  DELETE_TODO: 'deleteTodo',
  DRAG_ITEM: 'dragItem',
  SHOW_MODAL: 'showModal',
  INIT_MODAL: 'initModal',
  AUTH_SIGNIN: 'auth/signin',
  AUTH_LOGIN: 'auth/login',
  AUTH_LOGOUT: 'auth/logout',
  AUTH_USERINFO: 'auth/userInfo',
  GROUP_ADD: 'group/add',
  GROUP_LIST: 'group/list',
  ITEM_LIST: 'item/list',
  ITEM_ADD: 'item/add',
  ITEM_DELETE: 'item/delete',
}
